import React, { useCallback, useEffect, useRef, useState } from 'react';
import axios from 'axios';
import { MessageCircle, Send, X } from 'lucide-react';
import { useTheme } from '../../Context/ThemeContext';

export default function FeedbackChat({ ticket, onClose, embedded = false, onRead, onSent }) {
  const { theme } = useTheme(); const dark = theme === 'bg-skin-black';
  const [messages,setMessages]=useState([]), [draft,setDraft]=useState(''), [loading,setLoading]=useState(true), [sending,setSending]=useState(false), [error,setError]=useState('');
  const [closed,setClosed]=useState(['completed','declined'].includes(ticket.status)); const endRef=useRef(null);
  const onReadRef=useRef(onRead); const onSentRef=useRef(onSent);
  useEffect(()=>{onReadRef.current=onRead;onSentRef.current=onSent;},[onRead,onSent]);
  const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{const{data}=await axios.get(`/feedback/items/${ticket.id}/messages`);setMessages(data.messages??[]);setClosed(Boolean(data.closed));setError('');onReadRef.current?.();}catch(e){if(!quiet)setError(e.response?.data?.message||'Unable to load this conversation.');}finally{if(!quiet)setLoading(false);}},[ticket.id]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const poll=()=>document.visibilityState==='visible'&&load(true);const timer=setInterval(poll,10000);document.addEventListener('visibilitychange',poll);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',poll);};},[load]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'});},[messages.length]);
  const send=async(e)=>{e.preventDefault();if(!draft.trim()||sending||closed)return;setSending(true);setError('');try{const{data}=await axios.post(`/feedback/items/${ticket.id}/messages`,{message:draft});setMessages(c=>[...c,data.message]);setDraft('');onSentRef.current?.();}catch(x){setError(x.response?.data?.message||'Unable to send your message.');}finally{setSending(false);}};
  const body=<div className={`flex min-h-0 flex-col ${embedded?'mt-5 h-[430px]':'h-[min(78vh,620px)]'}`}><div className="flex items-center justify-between border-b border-current/10 pb-3"><div><h2 className="flex items-center gap-2 text-sm font-bold"><MessageCircle size={16}/>Support conversation</h2><p className="mt-1 text-[11px] text-[#787b86]">{ticket.title}</p></div>{onClose&&<button onClick={onClose} aria-label="Close conversation" className="rounded-md p-2 hover:bg-current/10"><X size={17}/></button>}</div><div className="min-h-0 flex-1 space-y-3 overflow-y-auto py-4" aria-live="polite">{loading?<p className="text-xs text-[#787b86]">Loading conversation…</p>:!messages.length?<p className="py-12 text-center text-xs text-[#787b86]">No messages yet. Start the conversation below.</p>:messages.map(m=><div key={m.id} className={`flex ${m.mine?'justify-end':'justify-start'}`}><div className={`max-w-[85%] rounded-xl px-3 py-2 ${m.mine?'bg-[#2dd4bf] text-white':dark?'bg-[#2a2e39]':'bg-slate-100'}`}><div className="text-[10px] font-semibold opacity-70">{m.mine?'You':m.user?.name||'Support'}</div><p className="whitespace-pre-wrap break-words text-sm">{m.message}</p><time className="mt-1 block text-[9px] opacity-60">{new Date(m.createdAt).toLocaleString()}</time></div></div>)}<div ref={endRef}/></div>{error&&<p className="mb-2 rounded-md bg-red-500/10 p-2 text-xs text-red-400">{error}</p>}{closed?<p className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-500">This ticket is closed. An administrator must reopen it before new messages can be sent.</p>:<form onSubmit={send} className="flex gap-2"><textarea aria-label="Message" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={2000} rows={2} required className={`min-w-0 flex-1 resize-none rounded-lg border p-3 text-sm outline-none focus:border-[#2dd4bf] ${dark?'border-[#2a2e39] bg-[#0b0e14]':'border-slate-200 bg-slate-50'}`} placeholder="Write a message…"/><button disabled={sending||!draft.trim()} className="self-stretch rounded-lg bg-[#2dd4bf] px-4 text-white disabled:opacity-50" aria-label="Send message"><Send size={16}/></button></form>}</div>;
  if(embedded)return body;
  return <div className="fixed inset-0 z-[10020] flex items-end justify-center bg-black/60 p-3 sm:items-center" onMouseDown={e=>e.target===e.currentTarget&&onClose?.()}><section role="dialog" aria-modal="true" className={`w-full max-w-xl rounded-xl border p-5 shadow-2xl ${dark?'border-[#2a2e39] bg-[#131722] text-white':'border-slate-200 bg-white text-slate-900'}`}>{body}</section></div>;
}
