import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Head, router } from '@inertiajs/react';
import axios from 'axios';
import { AlertTriangle, Check, CheckCircle2, Clock3, Eye, EyeOff, KeyRound, LockKeyhole, ShieldCheck, X } from 'lucide-react';
import { useTheme } from '../../Context/ThemeContext';

function SecureField({ label, name, value, onChange, error, autoComplete }) {
    const [visible, setVisible] = useState(false);
    return <label className="block"><span className="mb-1.5 block text-xs font-semibold">{label}</span><div className={`flex h-11 items-center rounded-lg border transition focus-within:border-[#2dd4bf] ${error ? 'border-red-500' : 'border-[#2a2e39]'}`}><LockKeyhole size={16} className="ml-3 text-[#787b86]"/><input type={visible?'text':'password'} name={name} value={value} onChange={onChange} autoComplete={autoComplete} className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none"/><button type="button" onClick={()=>setVisible((current)=>!current)} className="mr-2 rounded-md p-2 text-[#787b86] hover:bg-white/10" aria-label={visible?`Hide ${label}`:`Show ${label}`}>{visible?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>{error&&<span className="mt-1 block text-xs text-red-400">{error}</span>}</label>;
}

export default function ForceChangePassword() {
    const { theme } = useTheme();
    const isDark = theme === 'bg-skin-black';
    const [form,setForm]=useState({current_password:'',new_password:'',confirm_password:''});
    const [loading,setLoading]=useState(false);
    const [checkingWaive,setCheckingWaive]=useState(false);
    const [canWaive,setCanWaive]=useState(false);
    const [error,setError]=useState('');
    const [showSuccess,setShowSuccess]=useState(false);
    const [countdown,setCountdown]=useState(3);
    const signingOut=useRef(false);
    const signOut=useCallback(()=>{if(signingOut.current)return;signingOut.current=true;router.post('/logout');},[]);

    useEffect(()=>{axios.post('/check-password',{current_password:'qwerty'}).then(({data})=>setCanWaive(!data.success)).catch(()=>setCanWaive(false));},[]);
    const checks=useMemo(()=>({length:form.new_password.length>=8,uppercase:/[A-Z]/.test(form.new_password),lowercase:/[a-z]/.test(form.new_password),number:/\d/.test(form.new_password),special:/[!@#$%^&*(),.?":{}|<>;]/.test(form.new_password)}),[form.new_password]);
    const strong=Object.values(checks).every(Boolean); const matches=form.confirm_password!==''&&form.new_password===form.confirm_password; const canSubmit=form.current_password&&strong&&matches&&!loading;

    useEffect(()=>{if(!showSuccess)return undefined;if(countdown<=0){signOut();return undefined;}const timer=window.setTimeout(()=>setCountdown((current)=>current-1),1000);return()=>window.clearTimeout(timer);},[countdown,showSuccess,signOut]);
    const change=(event)=>{setError('');setForm((current)=>({...current,[event.target.name]:event.target.value}));};
    const submit=async(event)=>{event.preventDefault();if(!canSubmit)return;setLoading(true);setError('');try{const {data}=await axios.post('/save-change-password',form);if(data?.status!=='success'){setError(data?.message||'Unable to change your password.');return;}setCountdown(3);setShowSuccess(true);}catch(requestError){setError(requestError.response?.data?.message||'Unable to change your password.');}finally{setLoading(false);}};
    const waive=async()=>{setCheckingWaive(true);setError('');try{const check=await axios.post('/check-waive');if(check.data?.status){setError(check.data.message||'The password change can no longer be waived.');return;}const {data}=await axios.post('/waive-change-password');if(data?.status!=='success'){setError(data?.message||'Unable to waive the password change.');return;}router.visit('/workspace');}catch(requestError){setError(requestError.response?.data?.message||'Unable to verify the waiver.');}finally{setCheckingWaive(false);}};
    const criteria=[['length','At least 8 characters'],['uppercase','One uppercase letter'],['lowercase','One lowercase letter'],['number','One number'],['special','One special character']];
    const panel=isDark?'border-[#2a2e39] bg-[#131722] text-white':'border-slate-200 bg-white text-slate-900';

    return <><Head title="Security update required"/><div className="fixed inset-0 z-[190] flex items-center justify-center overflow-y-auto bg-[#070a10]/90 p-3 backdrop-blur-sm sm:p-6"><div className={`my-auto grid w-full max-w-4xl overflow-hidden rounded-2xl border shadow-2xl lg:grid-cols-[.85fr_1.15fr] ${panel}`} role="dialog" aria-modal="true" aria-labelledby="force-password-title">
        <aside className="relative overflow-hidden bg-[#2dd4bf] p-7 text-white sm:p-9"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-white/10"/><div className="relative"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-white/15"><AlertTriangle size={23}/></span><div className="mt-7 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider"><ShieldCheck size={13}/> Security action required</div><h1 id="force-password-title" className="mt-4 text-3xl font-bold leading-tight">Create a secure password to continue.</h1><p className="mt-4 text-sm leading-7 text-blue-100">Your account is using a temporary password or has reached its scheduled security update. Complete this step before returning to the trading workspace.</p><div className="mt-8 space-y-3 text-xs text-blue-50">{['Protects saved charts and drawings','Protects replay sessions and journals','Signs out other access after the update'].map((item)=><div key={item} className="flex gap-2"><Check size={15}/>{item}</div>)}</div></div></aside>
        <form onSubmit={submit} className="p-6 sm:p-9"><div className="mb-6"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-[#5eead4]"><KeyRound size={15}/>Password security</div><h2 className="mt-2 text-2xl font-bold">Update your password</h2><p className="mt-1 text-xs text-[#787b86]">All requirements must be completed before continuing.</p></div><div className="space-y-4"><SecureField label="Current or temporary password" name="current_password" value={form.current_password} onChange={change} autoComplete="current-password"/><SecureField label="New password" name="new_password" value={form.new_password} onChange={change} autoComplete="new-password"/><div className={`grid gap-2 rounded-lg border p-3 sm:grid-cols-2 ${isDark?'border-[#2a2e39] bg-[#0b0e14]':'border-slate-200 bg-slate-50'}`}>{criteria.map(([key,label])=><div key={key} className={`flex items-center gap-2 text-[11px] ${checks[key]?'text-emerald-400':'text-[#787b86]'}`}><span className={`flex h-4 w-4 items-center justify-center rounded-full ${checks[key]?'bg-emerald-500/15':'bg-slate-500/10'}`}>{checks[key]?<Check size={11}/>:<X size={10}/>}</span>{label}</div>)}</div><SecureField label="Confirm new password" name="confirm_password" value={form.confirm_password} onChange={change} autoComplete="new-password" error={form.confirm_password&&!matches?'Passwords do not match.':''}/></div>{error&&<div className="mt-4 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-400">{error}</div>}<button disabled={!canSubmit} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#2dd4bf] text-sm font-bold text-white hover:bg-[#14b8a6] disabled:opacity-40"><KeyRound size={16}/>{loading?'Updating password…':'Update password and continue'}</button>{canWaive&&<button type="button" onClick={waive} disabled={checkingWaive||loading} className="mt-2 flex h-10 w-full items-center justify-center gap-2 rounded-lg text-xs font-semibold text-[#787b86] hover:bg-white/5 disabled:opacity-40"><Clock3 size={14}/>{checkingWaive?'Checking waiver…':'Remind me later'}</button>}<p className="mt-3 text-center text-[10px] text-[#787b86]">After changing your password, you will be signed out for security.</p></form>
    </div></div>{showSuccess&&<div className="fixed inset-0 z-[230] flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm"><div className={`w-full max-w-sm rounded-xl border p-7 text-center shadow-2xl ${panel}`} role="dialog" aria-modal="true" aria-labelledby="force-success-title"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-500/15 text-emerald-400"><CheckCircle2 size={28}/></span><h2 id="force-success-title" className="mt-5 text-xl font-bold">Password updated</h2><p className="mt-2 text-sm text-[#787b86]">Your account is secure. Signing you out in</p><div className="mx-auto mt-4 flex h-16 w-16 items-center justify-center rounded-full border-4 border-[#2dd4bf]/25 text-2xl font-bold text-[#5eead4]">{countdown}</div><button type="button" onClick={signOut} className="mt-5 text-xs font-semibold text-[#2dd4bf] hover:underline">Sign out now</button></div></div>}</>;
}
